### PR TITLE
Add support for parsing @apply rules.

### LINKED ISSUE #8: [feature request] Support @apply
The `@apply` rule is a [proposed spec](https://tabatkins.github.io/specs/css-apply-rule/#at-ruledef-apply) for implementing native mixins in CSS on top of [CSS Custom Properties](https://github.com/Microsoft/vscode-css-languageservice/issues/7).

It allows declarations like the following:

```css
body {
  @apply --my-theme;
}
```

This sees real world usage today, primarily from users of the Polymer library, which ships a polyfill. As of VSCode 1.7.1, this is a syntax error.

### PR DESCRIPTION
**Pull request by rictic**
Follows the proposed (WIP) spec as it exists today at https://tabatkins.github.io/specs/css-apply-rule/#using

Fixes #8

### CODE REVIEW

**Comment by rictic** [comment]
I've signed the Microsoft CLA, and contributed to other Microsoft repos, e.g. https://github.com/Microsoft/TSJS-lib-generator/pull/151

**Comment by rictic** [comment]
Please let me know anything I can do to help this land!

I tried to make the change minimal, and follow the conventions of the repo.

**Comment by aeschli** [comment]
@rictic Changes look good. Any reason why `endOfAtApply` and `semicolonPosition` are remembered?

**Comment by rictic** [comment]
Just trying to follow the conventions. `AbstractDeclaration` tracks `colonPosition` and `semicolonPosition` and those were the closest analogs for `@apply`. Might have been cargo culting though, I didn't track down how those were used.

**Comment by rictic** [comment]
If you like I could drop `endOfAtApply` and `semicolonPosition`, or hook them into other parts of the code. Just let me know!

**Comment by abdonrd** [comment]
Yay! Thanks @rictic!

**Comment by aeschli** [comment]
Thanks @rictic . I polished the code a bit and simplified it. Removed the endOfAtApply and semicolonPosition, and also took away the test for --. This can better be done by a linter extension.

Thanks a lot for the contribution and sorry for the wait.

**Pull request merged**
