### PR TITLE
Add Mixin proposals

### PR DESCRIPTION
**Pull request by mrmlnc**
Source: #16

This PR adds:

  * Proposals for Mixins only after `@include` keyword

### CODE REVIEW

**Comment by mrmlnc** [comment]
Hmmm, I don't see ability to handling nested selectors for Mixins in Less.

```less
.mixin(@a: 1, @b) { content: @a + @b; }; .| // SimpleSelector
.mixin(@a: 1, @b) { content: @a + @b; }; .test { .|} // Declarations
.mixin(@a: 1, @b) { content: @a + @b; }; .test { .| // Nothing
```

**Comment by aeschli** [comment]
@mrmlnc Thank a lot!
I had recreate the commit to merge the changes. Also I made a few (mostly cosmetic) changes.

**Comment by mrmlnc** [comment]
@aeschli,

Yeap, this is good 👍. But what to do with Mixins in Less? We have three contexts and one of them does not exist in the AST.

**Comment by aeschli** [comment]
For LESS we need to override 'parseRuleset' to detect rulesets with selectors that are valid mixin declarations and annotate the selector identifier.
On the reference side, we get MixinReference Nodes already for .abc and #abc. What is the 3rd context?

**Comment by mrmlnc** [comment]
Now AST contains all Mixins in the Less file. Sorry, I was not entirely correct.

The problem is that Mixin can be called in different contexts:

  1. `SimpleSelector`

  ```less
  .mixin() {}
  .m|
  ```

  2. `Declarations`

  ```less
  .mixin() {}
  .test {
    .m|
  }
  ```

  3. Just case, not context.

  ```less
  .mixin() {}
  .test {
    .m|
  // without }
  ```

**Pull request closed without merging**
