### PR TITLE
Update `beautify-css`

### PR DESCRIPTION
**Pull request by romainmenke**
fixes : https://github.com/microsoft/vscode-css-languageservice/issues/333

The changelog for `js-beautify` `1.14.8` : https://github.com/beautify-web/js-beautify/blob/main/CHANGELOG.md#v1148

### CODE REVIEW

**Comment by focussing** [comment]
Does anyone has an idea when this issue is solved?

**Review by holygekko — APPROVED** [review]

**Review by Itemshopp — APPROVED** [review]

**Comment by romainmenke** [comment]
@aeschli Maybe this can be part of the next release of VSCode, if you have time to review these changes? 🙇

**Review by T-Zahil — APPROVED** [review]

**Comment by floroz** [comment]
I have this workaround for those who are waiting this PR to be merged

 https://github.com/beautify-web/js-beautify/issues/2012#issuecomment-1660225405

**Comment by romainmenke** [comment]
please try to keep this PR on topic and focussed towards getting this merged :)  
I can't unsubscribe here in case maintainers have feedback.

The linked issue would be a good place to add extra information.

Also please refrain from approving pull requests if you aren't a maintainer.
I understand that a lot of people want to see this change ship but try to be mindful of other people's inbox 🙇

**Comment by romainmenke** [comment]
@connor4312 Sorry to ping you, and unsure if this project is something you are actively involved with. I saw that you recently did reviews here, so I am hoping this is ok.

It would be awesome if this repository could receive some attention and if some changes could be reviewed. One of them is this one.

Is this something you can help with or do you know who might?

**Comment by connor4312** [comment]
The maintainer of this repo is on vacation but will be back in a couple weeks, he will review this after his return. The next release is not happening until the beginning of next month anyway.

**Comment by romainmenke** [comment]
This is no longer needed.

Was superseded by : https://github.com/microsoft/vscode-css-languageservice/pull/361/files

**Pull request closed without merging**
