### PR TITLE
[WIP] Use MDN to enhance CSS LS. Part of #68

### PR DESCRIPTION
**Pull request by octref**
This PR:

- Adds dependency on `mdn-data` (can we switch to yarn.lock instead of package-lock.json entirely?)
- Generate `browsers.ts` by combining VSC and MDN data, while giving preference to VSC data
- Show `syntax` and `status` in completion item's documentation.

Questions:

- How should we generate restrictions / values? Currently for any of the new properties that MDN data introduces, we have no restriction and the value auto completion is inaccurate.
- Our data contains [239 properties](https://github.com/Microsoft/vscode-css-languageservice/issues/68#issuecomment-380172011) that's not in MDN Data. However, a majority of them are actually SVG properties (tracked in https://github.com/mdn/data/issues/59). We can either
  - Hand curate the 239 properties to tell which ones are not SVG related, and mark those as deprecated / obsolete.
  - Wait for https://github.com/mdn/data/issues/59

### CODE REVIEW

**Comment by aeschli** [comment]
Note that`browsers.js` should be as small as possible. vscode-css-languageservice is also used in the browser (for monaco) and we want the minimal memory footprint as well as download package size.
So `browsers.js` should only keep the properties that are used in the code.

**Comment by aeschli** [comment]
I like the use of status. Maybe we should omit `"status": "standard"` in order to make browser.js smaller.

**Comment by octref** [comment]
> Maybe we should omit "status": "standard" in order to make browser.js smaller.

@aeschli Sure, I can remove it together with a bunch of other unused properties.

@chriseppstein Yes, I submitted license review request for mdn/data. Before the review passes we won't ship the change. Meanwhile, can you chime in at https://github.com/mdn/data/issues/199 for your concerns?

**Comment by octref** [comment]
@chriseppstein 

https://www.mozilla.org/en-US/MPL/2.0/FAQ/

> Q11: How 'viral' is the MPL? If I use MPL-licensed code in my proprietary application, will I have to give all the source code away?
No. The license requires that Modifications (as defined in Section 1.10 of the license) must be licensed under the MPL and made available to anyone to whom you distribute the Source Code. However, new files containing no MPL-licensed code are not Modifications, and therefore do not need to be distributed under the terms of the MPL, even if you create a Larger Work (as defined in Section 1.7) by using, compiling, or distributing the non-MPL files together with MPL-licensed files. This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.

We don't do any modification to the original mdn/data source, so vscode-css-languageservice could still be shared under MIT license.

**Comment by chriseppstein** [comment]
So, the legal definition of modification isn’t the same as a developer’s definition. I haven’t reviewed this PR in depth yet, but according to the lawyers I’ve worked with there’s a number of build time transformations that meet the legal definition of “modification” and would require a dual license.

If you don’t do anything like that, it’s still something that will require an ongoing attention towards.

**Comment by octref** [comment]
@chriseppstein Thanks, I've opened https://github.com/mdn/data/issues/210

**Pull request merged**
